# Generated by Django 2.1.3 on 2019-04-09 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhunt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userhunt',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
