# Generated by Django 2.2 on 2019-04-09 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('checkpoint_amount', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('hunt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunts', to='hunt_app.Hunt')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('hunt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='hunt_app.Hunt')),
            ],
        ),
    ]
