# Generated by Django 2.2 on 2019-04-09 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0002_auto_20190409_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhunt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userhunt',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
