# Generated by Django 2.2 on 2019-04-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0004_auto_20190409_1958'),
        ('hunt_app', '0002_auto_20190409_1956'),
    ]

    operations = [
    ]
